package com.github.gv2011.dependencyanalyser.impl;

import static java.util.Objects.requireNonNull;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.util.Properties;

import com.github.gv2011.dependencyanalyser.api.Version;
import com.github.gv2011.util.ann.Nullable;
import com.github.gv2011.util.icol.Opt;

/**
 * Reads a Maven artifact's own pom.properties from the classpath
 * (META-INF/maven/&lt;groupId&gt;/&lt;artifactId&gt;/pom.properties).
 *
 * <p><b>Availability:</b>
 * <ul>
 * <li>This file is generated by the {@code package} phase - specifically,
 *     by maven-jar-plugin's archiver, which bakes it directly into the
 *     built jar. It is never copied into {@code target/classes} as an
 *     intermediate step, so it does not exist on a classpath built from
 *     that directory alone.
 * <li>In Eclipse: generated either by an external {@code mvn} build or by
 *     m2e's own embedded build mechanism - in practice, run Maven &gt;
 *     Update Project. A plain incremental Eclipse build (without that)
 *     does not create or refresh this file.
 * <li>Under Maven itself: the maven-surefire-plugin (unit tests) binds to
 *     the {@code test} phase, which runs before {@code package}, and uses
 *     {@code target/classes} directly - so this is absent
 *     ({@link Opt#empty()}, not an error) during a plain {@code mvn test}
 *     run. The maven-failsafe-plugin (integration tests) binds its
 *     {@code integration-test} goal to the {@code integration-test}
 *     phase, which runs after {@code package} - and, unlike surefire, by
 *     default prefers the packaged jar file over {@code target/classes}
 *     on the classpath. Since that jar does contain pom.properties, it is
 *     present by the time an integration test runs.
 * </ul>
 */
public final class PomPropertiesReader {

  public static final String VERSION_PROPERTY = "version";

  private final String groupId;
  private final String artifactId;

  public PomPropertiesReader(final String groupId, final String artifactId) {
    this.groupId = groupId;
    this.artifactId = artifactId;
  }

  public Opt<Properties> readPomProperties() {
    final String resourcePath = "/META-INF/maven/" + groupId + "/" + artifactId + "/pom.properties";
    try(@Nullable InputStream in = getClass().getResourceAsStream(resourcePath)) {
      return in==null ? Opt.empty() : Opt.of(loadProperties(in));
    }
    catch(final IOException e) {
      throw new UncheckedIOException(e);
    }
  }

  public Opt<Version> readVersion() {
    return readPomProperties()
      .map(p -> requireNonNull(p.getProperty(VERSION_PROPERTY)))
      .map(VersionImpl::parse)
    ;
  }

  private static Properties loadProperties(final InputStream in) throws IOException {
    final Properties properties = new Properties();
    properties.load(in);
    return properties;
  }

}
