package com.github.gv2011.dependencyanalyser.impl;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.util.Objects;
import java.util.Properties;

import com.github.gv2011.dependencyanalyser.api.Version;
import com.github.gv2011.util.icol.Opt;

/**
 * Reads a Maven artifact's own pom.properties from the classpath
 * (META-INF/maven/&lt;groupId&gt;/&lt;artifactId&gt;/pom.properties) - the same
 * mechanism and location the previous version of this project used for
 * self-version-discovery.
 *
 * <p><b>Availability:</b>
 * <ul>
 * <li>This file is generated by a real Maven build (embedded into the
 *     built jar) - not present until the artifact has actually gone
 *     through the package phase.
 * <li>In Eclipse: only present after a real Maven build has produced it
 *     and Eclipse has picked that up - in practice, run Maven &gt; Update
 *     Project first. Simply having the project open, or a plain
 *     incremental Eclipse build, does not create or refresh this file.
 * <li>Under Maven itself: absent during a plain {@code mvn test} run
 *     (which runs before packaging) - {@link Opt#empty()}, not an error.
 *     Present by the time an integration test runs (failsafe's
 *     integration-test/verify phases come after package).
 * </ul>
 */
public final class PomPropertiesReader {

  public static final String VERSION_PROPERTY = "version";

  private final String groupId;
  private final String artifactId;

  public PomPropertiesReader(final String groupId, final String artifactId) {
    this.groupId = groupId;
    this.artifactId = artifactId;
  }

  public Opt<Properties> readPomProperties() {
    final String resourcePath = "/META-INF/maven/" + groupId + "/" + artifactId + "/pom.properties";
    try(InputStream in = getClass().getResourceAsStream(resourcePath)) {
      return in==null ? Opt.empty() : Opt.of(loadProperties(in));
    }
    catch(final IOException e) {
      throw new UncheckedIOException(e);
    }
  }

  public Opt<Version> readVersion() {
    return readPomProperties()
      .map(p -> Objects.requireNonNull(p.getProperty(VERSION_PROPERTY)))
      .map(VersionImpl::parse)
    ;
  }

  private static Properties loadProperties(final InputStream in) throws IOException {
    final Properties properties = new Properties();
    properties.load(in);
    return properties;
  }

}
