package com.github.gv2011.dependencyanalyser.impl;

import java.util.Objects;

import com.github.gv2011.dependencyanalyser.api.Version;
import com.github.gv2011.util.icol.Opt;

/**
 * This reactor's own version, read from dependency-analyser-implementation's
 * own installed pom.properties.
 *
 * <p><b>Assumption:</b> every module in this reactor shares the same
 * version (no module overrides its parent's version) - so this is also
 * the correct version for any other module in the reactor, without
 * needing to read that module's own pom.properties separately.
 *
 * <p><b>Availability - read this before using {@link #get()}:</b>
 * <ul>
 * <li>Requires dependency-analyser-implementation's own pom.properties to
 *     be present on the classpath, at
 *     META-INF/maven/com.github.gv2011/dependency-analyser-implementation/
 *     pom.properties. This file is generated by a real Maven build; it is
 *     not something this project writes itself.
 * <li>In Eclipse: only present after a real Maven build has produced it
 *     and Eclipse has picked that up - in practice, run Maven &gt; Update
 *     Project first. Simply having the project open, or a plain
 *     incremental Eclipse build, does not create or refresh this file.
 * <li>Under Maven itself: only present once this module has gone through
 *     the package phase. Absent during a plain {@code mvn test} run
 *     (which runs before packaging) - {@link Opt#empty()}, not an error.
 *     Present by the time an integration test runs (failsafe's
 *     integration-test/verify phases come after package).
 * </ul>
 */
public final class ReactorVersion {

  private static final String GROUP_ID = "com.github.gv2011";
  private static final String ARTIFACT_ID = "dependency-analyser-implementation";

  private ReactorVersion(){}

  public static Opt<Version> get() {
    return new PomPropertiesReader(GROUP_ID, ARTIFACT_ID).readPomProperties()
      .map(p -> Objects.requireNonNull(p.getProperty(PomPropertiesReader.VERSION_PROPERTY)))
      .map(VersionImpl::parse)
    ;
  }

}
