package com.github.gv2011.dependencyanalyser.impl;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;

import org.junit.jupiter.api.Test;

import com.github.gv2011.dependencyanalyser.api.DependencyDeclaration;
import com.github.gv2011.dependencyanalyser.api.PomDependencyDeclarations;
import com.github.gv2011.util.icol.ISet;

/**
 * Parses a hand-written pom.xml, committed directly at
 * src/test/resources/sample-pom.xml - not generated by any real Maven
 * build. Deliberately covers: an own version-bearing {@code <parent>}, a
 * plain {@code <dependencies>} entry with a version, a plain
 * {@code <dependencies>} entry without one (relying on
 * {@code dependencyManagement} - must not appear in the result), a plain
 * {@code <dependencyManagement>} entry, and a BOM import
 * ({@code <scope>import</scope><type>pom</type>}).
 *
 * <p>Deliberately does NOT cover the "not yet implemented" edge cases
 * (own or parent version inherited/omitted) - see
 * PomDependencyDeclarationsParserIT for that, against example's real,
 * unmodified pom.xml, which happens to hit exactly one of them.
 */
class PomDependencyDeclarationsParserTest {

  @Test
  void parsesSamplePom() {
    final PomDependencyDeclarations declarations =
      PomDependencyDeclarationsParser.parse(readResource("/sample-pom.xml"))
    ;

    assertThat(declarations.coordinates().identity().groupId(), is("com.example"));
    assertThat(
      declarations.coordinates().identity().artifactId(), is("sample-pom-declarations-fixture")
    );
    assertThat(declarations.coordinates().version().toString(), is("1.0.0-test"));

    assertThat("expected a <parent>", declarations.parent().isPresent(), is(true));
    assertThat(declarations.parent().get().identity().artifactId(), is("sample-parent"));
    assertThat(declarations.parent().get().version().toString(), is("9.9.9"));

    final ISet<DependencyDeclaration> deps = declarations.dependencyDeclarations();
    assertThat(
      "the un-versioned plain <dependencies> entry must not appear; found: " + deps,
      deps.size(),
      is(3)
    );

    final DependencyDeclaration direct = findByArtifactId(deps, "slf4j-api");
    assertThat(direct.managed(), is(false));
    assertThat(direct.isBomImport(), is(false));
    assertThat(direct.coordinates().version().toString(), is("2.0.19"));

    final DependencyDeclaration managed = findByArtifactId(deps, "managed-only-dependency");
    assertThat(managed.managed(), is(true));
    assertThat(managed.isBomImport(), is(false));
    assertThat(managed.coordinates().version().toString(), is("3.1.4"));

    final DependencyDeclaration bomImport = findByArtifactId(deps, "sample-bom");
    assertThat(bomImport.managed(), is(true));
    assertThat(bomImport.isBomImport(), is(true));
    assertThat(bomImport.coordinates().version().toString(), is("5.0.0"));
  }

  private static DependencyDeclaration findByArtifactId(
    final ISet<DependencyDeclaration> declarations, final String artifactId
  ) {
    return declarations.stream()
      .filter(d -> d.coordinates().identity().artifactId().equals(artifactId))
      .findFirst()
      .orElseThrow(() -> new AssertionError("No declaration found for artifactId " + artifactId))
    ;
  }

  private static String readResource(final String path) {
    try(InputStream in = PomDependencyDeclarationsParserTest.class.getResourceAsStream(path)) {
      if(in==null) {
        throw new IllegalStateException("Test resource not found: " + path);
      }
      return new String(in.readAllBytes(), StandardCharsets.UTF_8);
    }
    catch(final IOException e) {
      throw new UncheckedIOException(e);
    }
  }

}
